apiVersion: v1
kind: Service
metadata:
  labels:
    service: opensearch-dashboards
  name: opensearch-dashboards
  namespace: opensearch
spec:
  ports:
  - name: "5601"
    port: 80
    targetPort: 5601
  selector:
    service: opensearch-dashboards
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: opensearch-node
  name: opensearch-node
  namespace: opensearch
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  - name: "9600"
    port: 9600
    targetPort: 9600
  selector:
    service: opensearch-node
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: opensearch-dashboards
  name: opensearch-dashboards
  namespace: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      service: opensearch-dashboards
  strategy: {}
  template:
    metadata:
      labels:
        network/opensearch-net: "true"
        service: opensearch-dashboards
    spec:
      containers:
      - env:
        - name: OPENSEARCH_HOSTS
          value: https://opensearch-node1:9200
        image: opensearchproject/opensearch-dashboards:1.2.0
        name: opensearch-dashboards
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5601
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: opensearch-node
  name: opensearch-node
  namespace: opensearch
spec:
  replicas: 3
  selector:
    matchLabels:
      service: opensearch-node
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/opensearch-net: "true"
        service: opensearch-node
    spec:
      containers:
      - env:
        - name: OPENSEARCH_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: bootstrap.memory_lock
          value: "false"
        - name: cluster.initial_master_nodes
          value: opensearch-node
        - name: cluster.name
          value: opensearch-cluster
        - name: discovery.seed_hosts
          value: opensearch-node
        - name: node.name
          value: opensearch-node
        image: opensearchproject/opensearch:1.2.0
        name: opensearch-node
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
        - containerPort: 9600
        resources: {}
      restartPolicy: Always
status: {}
