---
# Source: opensearch/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: opensearch-cluster-master
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/component: opensearch-cluster-master
  namespace: opensearch
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: opensearch
  ports:
  - name: http
    protocol: TCP
    port: 9200
  - name: transport
    protocol: TCP
    port: 9300
---
# Source: opensearch/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: opensearch-cluster-master-headless
  labels:
    
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/component: opensearch-cluster-master
  namespace: opensearch
spec:
  clusterIP: None # This is needed for statefulset hostnames like opensearch-0 to resolve
  # Create endpoints also if the related pod isn't ready
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: opensearch
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
